---
title: "Aerodynamic Canopy Height (forest example)"
output: github_document
author: Housen Chu
date: 2018-04-26
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F)
path<-getwd()
DataDir<-paste(path,"\\Input\\",sep="")
OutDir<-paste(path,"\\Output\\",sep="")
```
### Load required packages and functions
```{r include=T, message = F}
require(car)
require(MASS)
source("hc_ddb2.R")
#source("prevailing_WD.R")
source("z0dhc.ratio.gen.R")
source("math_util.R")
```
## User-defined parameters
### Workflow Control
```{r include=T,echo=T}
mdl.ver <- "R94"      # "R94", "SD00", or "FIXED" 
shuffle.run <- T      # resample data or not (TRUE/FALSE) when estimation ha, this is intended for error propagation 
plot.output <- T      # output plot (TRUE/FALSE)
file.output <- T      # output file (TRUE/FALSE)
lai.rs.use <- F       # first use Remote sensing LAI (TRUE) or BADM LAI (FALSE), LAI specified as below
grw.mo <- 3           # specify lenth of growing season in month, default as 3 months (~91 days based on RS.LAI)
sim.N <- 1000         # number of simulation for z0/h & d/h
```
### Site parameters 
```{r include=T,echo=T}
case <- "US-Oho_2011"            # 6-digit Fluxnet/AmeriFlux Site ID (CC-XXX), 4-digit year, separate by "_" 
res <- "HH"                      # Temporal resolution of the flux/met file ("HH"/"HR"), half-hourly/hourly
ustr.u <- 1.0                    # upper bound of accepted USTAR (m/s)  
ustr.l <- 0.2                    # lower bound of accepted USTAR (m/s)
wd.u <- 0                        # upper bound of accepted WD (degree)
wd.l <- 90                       # lower bound of accepted WD (degree)
lai <- 4                         # LAI based on BADM
lai.rs <- 2.90                   # LAI based on Remote-Sensing product 
lai.i <- 144                     # starting date of full-foliated season, pre-processed based on Remote-Sensing LAI
lai.f <- 240                     # ending date of full-foliated season, pre-processed based on Remote-Sensing LAI
k <- 0.4                         # von Karman constant (0.4)
nos<-length(case)                # number of case
d.hr <- ifelse(res=="HH",48,24)  # handle hourly/half-hourly data
```
## Data input/output
```{r include=T,echo=T}
# read in pre-procesed/quality-controlled file 
data.org<-read.table(paste(DataDir,case,".csv",sep=""),header=T,sep=",",na.string=c("-9999"))

# maximun of zm within the data period, 
#   this is used for setting the upper bound of accepted ha estimation in hc_ddb2 function
zmax<-max(data.org$zm_1,na.rm=T)

# prepare a composite table for storing output annual ha (without roughness sublayer correction)
#   with all sim.N estimates 
hc.com.out<-data.frame(SITE_ID = substr(case,start=1,stop=6),                    # 6-digit SITE ID
                       YR = as.numeric(substr(case,start=8,stop=nchar(case))),   # Year of estimate
                       zm.max = zmax,                                            # max measurement height in the data period    
                       N.ddb = NA,                                               # N of data available after all filtering
                       Nin.ddb = NA)                                             # N of data record in original file
hc.com.out<-cbind(hc.com.out,matrix(NA,nos,sim.N))                               # sim.N columns for storing all calculated ha

# prepare a composite table for storing output annual ha (with roughness sublayer correction)
hc.com.out2<-hc.com.out 

# rename the variable names, and grab a subset for further analysis
data.pre<-data.frame(DOY = data.org$DOY,                # Date of the year (1-366)
                     WS = data.org$WS_1,                # the mean wind speed (m/s)
                     USTAR = data.org$USTAR_1,          # friction velocity (m/s)
                     MO_LENGTH = data.org$MO_LENGTH_1,  # Obukhov length L (m) 
                     zm = data.org$zm_1,                # measurement height of WS, USTAR (m)
                     WD = data.org$WD_1)                # wind direction (degree from north)  
                     
```

### Data filtering   
```{r include=T,echo=T}    
# filtering data by setting USTAR thresholds
data.pre[!is.na(data.pre$USTAR)&data.pre$USTAR<ustr.l,c("USTAR","WS","MO_LENGTH")]<-NA
data.pre[!is.na(data.pre$USTAR)&data.pre$USTAR>ustr.u,c("USTAR","WS","MO_LENGTH")]<-NA

# filtering data by setting WD thresholds 
if(!is.na(wd.l)&!is.na(wd.u)){
  if(wd.l<wd.u){
    data.pre[!is.na(data.pre$WD)&data.pre$WD<wd.l,c("USTAR","WS","MO_LENGTH")]<-NA
    data.pre[!is.na(data.pre$WD)&data.pre$WD>wd.u,c("USTAR","WS","MO_LENGTH")]<-NA
  }else{
    data.pre[!is.na(data.pre$WD)&(data.pre$WD<wd.l&data.pre$WD>wd.u),c("USTAR","WS","MO_LENGTH")]<-NA
  }
}

# filtering data by setting MO_LENGTH thresholds
data.pre[!is.na(data.pre$MO_LENGTH)&data.pre$MO_LENGTH>1000,c("USTAR","WS","MO_LENGTH")]<-NA
data.pre[!is.na(data.pre$MO_LENGTH)&data.pre$MO_LENGTH<(-1000),c("USTAR","WS","MO_LENGTH")]<-NA

# adjust full-foliated season length, default as 3 months if not specified  
grw.mo.adj<-ceiling((90-grw.mo*30)/2)
doy.i<-ifelse(!is.na(lai.i),lai.i+grw.mo.adj,152+grw.mo.adj)
doy.f<-ifelse(!is.na(lai.f),lai.f-grw.mo.adj,243-grw.mo.adj)

# select the target full-foliated months
data.pre2<-data.pre[data.pre$DOY>=doy.i&data.pre$DOY<=doy.f,c("WS","USTAR","MO_LENGTH","zm")]

```

### Generte z0/h and d/h pairs
Generate `r sim.N` pairs of   
```{r include=T,echo=T}     
# Generate sim.N pairs of z0/h, d/h based on the selected model and prescribed LAI  
#   the sequence of LAI preference is controlled by lai.rs.use
if(lai.rs.use){ # use RS-based LAI first
  z0dhc.ratio<-z0dhc.ratio.gen(LAI=ifelse(!is.na(lai.rs),lai.rs,lai),
                               sim.N=sim.N,mdl.default=mdl.ver)  
}else{  # use site-specific LAI first
  z0dhc.ratio<-z0dhc.ratio.gen(LAI=ifelse(!is.na(lai),lai,lai.rs),
                               sim.N=sim.N,mdl.default=mdl.ver)  
}
```

### Main calculation for aerodynamic canopy height  
```{r include=T,echo=T}   
for(n in 1:sim.N){
  if(shuffle.run){
    if(n==1){
      shuffle.ls2<-c(1:nrow(data.pre2))  # original data set
    }else{
      shuffle.ls2<-sort(sample(c(1:nrow(data.pre2)),replace=T))  # shuffle with replacement
    }
  }else{
    shuffle.ls2<-c(1:nrow(data.pre2))  # original data set
  }  
  # ha estimation (without roughness sublayer correction)
  hc.ddb2.hold<-hc_ddb2(data.pre2[shuffle.ls2,],
                        zmax=zmax,
                        d.hr=d.hr,
                        coef1=z0dhc.ratio[n,1],
                        coef2=z0dhc.ratio[n,2],
                        lamda=1,
                        zm.cut=T)
  
  # ha estimation (with roughness sublayer correction)
  hc.ddb2.hold2<-hc_ddb2(data.pre2[shuffle.ls2,],
                         zmax=zmax,
                         d.hr=d.hr,
                         coef1=z0dhc.ratio[n,1],
                         coef2=z0dhc.ratio[n,2],
                         lamda=1.25,
                         zm.cut=T)
  
  hc.com.out[1,n+5]<-hc.ddb2.hold[[1]]
  hc.com.out2[1,n+5]<-hc.ddb2.hold2[[1]]
  hc.com.out$N.ddb<-hc.ddb2.hold[[9]]
  hc.com.out2$N.ddb<-hc.ddb2.hold2[[9]]
  hc.com.out$Nin.ddb<-hc.ddb2.hold[[10]]
  hc.com.out2$Nin.ddb<-hc.ddb2.hold2[[10]]
}

```

### Example plot 
```{r include=T,echo=F}   
if(plot.output&
   sum(!is.na(as.numeric(hc.com.out[1,5+c(1:sim.N)])))>=0.8*sim.N&
   sum(!is.na(as.numeric(hc.com.out2[1,5+c(1:sim.N)])))>=0.8*sim.N){
  
  par(oma=c(0,0,0,0),mar=c(4.5,4.5,1.5,0.5))
  hist(as.numeric(hc.com.out[1,5+c(1:sim.N)]),nclass=50,
       main=paste(hc.com.out$SITE_ID,hc.com.out$YR),
       xlab="ha (m)",xlim=c(0,1.2*zmax),ylim=c(0,sim.N/10),col="deepskyblue",border=NULL,lty=0)
  hist(as.numeric(hc.com.out2[1,5+c(1:sim.N)]),nclass=50,add=T,col="darkorange",border=NULL,lty=0)
  abline(v=median(as.numeric(hc.com.out[1,5+c(1:sim.N)]),na.rm=T),lwd=3,col="deepskyblue4")
  abline(v=median(as.numeric(hc.com.out2[1,5+c(1:sim.N)]),na.rm=T),lwd=3,col="darkorange4")
  legend(0,sim.N/10,legend=c(expression(lambda[rs]~'='~1.00),expression(lambda[rs]~'='~1.25)),
         fill=c("deepskyblue","darkorange"),border=NA,bty="n")
  
}

```

### Output the calculated ha  
```{r include=T,echo=T}   
if(file.output){  
  write.table(hc.com.out,paste(OutDir,case,"_yearly_grw",grw.mo,"mo_canopy-height1.csv",sep=""),sep=",",row.names=F)
  write.table(hc.com.out2,paste(OutDir,case,"_yearly_grw",grw.mo,"mo_canopy-height2.csv",sep=""),sep=",",row.names=F)
}

```

